#pragma once

///Debug Constants
#define DEBUG_SHOW_CONSOLE
#define DEBUG_SHOW_FPSCOUNTER
#define DEBUG_CONSOLE_OUTPUT
//#define DEBUG_DODGE_ENEMIES_COLLISIONS
#define DEBUG_REBUILD_FLOOR
#define DEBUG_ATTRIBUTE_MANIPULATION
//#define DEBUG_MAINVIEW_MANIPULATION
