#pragma once

///Debug Constants
#define DEBUG_SHOW_CONSOLE
#define DEBUG_SHOW_FPSCOUNTER
//#define DEBUG_SHOW_COLLISIONCHECKERS
//#define DEBUG_UNITS_VIEW
#define DEBUG_FLOOR_VIEW
#define DEBUG_CONSOLE_OUTPUT
#define DEBUG_BUTTONS_OUTPUT
//#define DEBUG_ATTACK_OUTPUT
#define DEBUG_PLAYER_STATS_OUTPUT
//#define DEBUG_CLOSE_CURRENT_ROOM
#define DEBUG_REBUILD_FLOOR
#define DEBUG_ATTRIBUTE_MANIPULATION
#define DEBUG_MAINVIEW_MANIPULATION
